nodeLinker: node-modules

packageExtensions:
  '@mdx-js/loader@*':
    peerDependencies:
      react: '*'
    peerDependenciesMeta:
      react:
        optional: true
  '@storybook/preset-create-react-app@*':
    peerDependencies:
      react-refresh: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      react-refresh:
        optional: false
      typescript:
        optional: true
      webpack:
        optional: true
  '@tools/ui-kit@*':
    peerDependencies:
      '@babel/core': '*'
      '@storybook/addons': '*'
      '@storybook/api': '*'
      '@storybook/components': '*'
      '@storybook/core-events': '*'
      babel-loader: '*'
      react-refresh: '*'
      stylelint: '*'
      stylelint-order: '*'
      stylelint-scss: '*'
    peerDependenciesMeta:
      '@babel/core':
        optional: true
      '@storybook/addons':
        optional: true
      '@storybook/api':
        optional: true
      '@storybook/components':
        optional: true
      '@storybook/core-events':
        optional: true
      babel-loader:
        optional: true
      stylelint:
        optional: true
      stylelint-order:
        optional: true
      stylelint-scss:
        optional: true
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: '*'
      eslint-plugin-import: '*'
    peerDependenciesMeta:
      eslint:
        optional: true
      eslint-plugin-import:
        optional: true
  eslint-config-react-app@*:
    peerDependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
    peerDependenciesMeta:
      '@babel/plugin-syntax-flow':
        optional: true
      '@babel/plugin-transform-react-jsx':
        optional: true
  react-dev-utils@*:
    peerDependencies:
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  react-scripts@*:
    peerDependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
      autoprefixer: '*'
    peerDependenciesMeta:
      '@babel/plugin-syntax-flow':
        optional: true
      '@babel/plugin-transform-react-jsx':
        optional: true
      autoprefixer:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: 'https://yarnplugins.com/echo-execute'
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://mskelton.dev/yarn-outdated/v2'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
